version = 1

[[annotations]]
path = ["**/*.robot", "**/*.png", "**/*.svg", "**/*.pem", "**/*.json"]
precedence = "closest"
SPDX-FileCopyrightText = "2024 3mdeb <contact@3mdeb.com>"
SPDX-License-Identifier = "Apache-2.0"
